python calculate_feature_importance_values.py ../results/fig4_curves_per_species_and_antibiotics/lr/Site_DRIAMS-A_Species_Escherichia_coli_Antibiotic_Ceftriaxone_Seed*
python calculate_feature_importance_values.py  ../results/fig4_curves_per_species_and_antibiotics/lr/Site_DRIAMS-A_Species_Klebsiella_pneumoniae_Antibiotic_Meropenem_Seed*
python calculate_feature_importance_values.py  ../results/fig4_curves_per_species_and_antibiotics/lr/Site_DRIAMS-A_Species_Staphylococcus_aureus_Antibiotic_Oxacillin_Seed*
