# antibiotic categorization
ab_cat_map = {'5-Fluorocytosine': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Amikacin': 'AMINOGLYCOSIDE ANTIBACTERIALS',
              'Aminoglycosides': 'AMINOGLYCOSIDE ANTIBACTERIALS',
              'Amoxicillin': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Amoxicillin-Clavulanic acid': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Amoxicillin-Clavulanic acid_uncomplicated_HWI': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Amphotericin B': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Ampicillin-Amoxicillin': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Anidulafungin': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Azithromycin': 'MACROLIDES, LINCOSAMIDES AND STREPTOGRAMINS',
              'Aztreonam': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Caspofungin': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Cefazolin': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Cefepime': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Cefixime': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Cefoxitin_screen': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Cefpodoxime': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Ceftazidime': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Ceftriaxone': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Cefuroxime': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Chloramphenicol': 'AMPHENICOLS',
              'Ciprofloxacin': 'QUINOLONE ANTIBACTERIALS',
              'Clarithromycin': 'MACROLIDES, LINCOSAMIDES AND STREPTOGRAMINS',
              'Clindamycin': 'MACROLIDES, LINCOSAMIDES AND STREPTOGRAMINS',
              'Colistin': 'OTHER ANTIBACTERIALS',
              'Cotrimoxazole': 'SULFONAMIDES AND TRIMETHOPRIM',
              'Daptomycin': 'OTHER ANTIBACTERIALS',
              'Doxycycline': 'TETRACYCLINES',
              'Ertapenem': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Erythromycin': 'MACROLIDES, LINCOSAMIDES AND STREPTOGRAMINS',
              'Fluconazole': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Fosfomycin': 'OTHER ANTIBACTERIALS',
              'Fosfomycin-Trometamol': 'OTHER ANTIBACTERIALS',
              'Fusidic acid': 'OTHER ANTIBACTERIALS',
              'Gentamicin': 'AMINOGLYCOSIDE ANTIBACTERIALS',
              'Gentamicin_high_level': 'AMINOGLYCOSIDE ANTIBACTERIALS',
              'Imipenem': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Itraconazole': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Levofloxacin': 'QUINOLONE ANTIBACTERIALS',
              'Linezolid': 'OTHER ANTIBACTERIALS',
              'Meropenem': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Meropenem_with_meningitis': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Meropenem_with_pneumonia': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Meropenem_without_meningitis': 'OTHER BETA-LACTAM ANTIBACTERIALS',
              'Metronidazole': 'OTHER ANTIBACTERIALS',
              'Micafungin': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Minocycline': 'TETRACYCLINES',
              'Moxifloxacin': 'QUINOLONE ANTIBACTERIALS',
              'Mupirocin': 'ANTIBIOTICS FOR TOPICAL USE',
              'Nitrofurantoin': 'OTHER ANTIBACTERIALS',
              'Norfloxacin': 'QUINOLONE ANTIBACTERIALS',
              'Oxacillin': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin_with_endokarditis': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin_with_meningitis': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin_with_other_infections': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin_with_pneumonia': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Penicillin_without_endokarditis': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Piperacillin-Tazobactam': 'BETA-LACTAM ANTIBACTERIALS, PENICILLINS',
              'Posaconazole': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              'Quinolones': 'QUINOLONE ANTIBACTERIALS',
              'Rifampicin': 'DRUGS FOR TREATMENT OF TUBERCULOSIS',
              'Rifampicin_1mg-l': 'DRUGS FOR TREATMENT OF TUBERCULOSIS',
              'Teicoplanin': 'OTHER ANTIBACTERIALS',
              'Teicoplanin_GRD': 'OTHER ANTIBACTERIALS',
              'Tetracycline': 'TETRACYCLINES',
              'Tigecycline': 'TETRACYCLINES',
              'Tobramycin': 'AMINOGLYCOSIDE ANTIBACTERIALS',
              'Vancomycin': 'OTHER ANTIBACTERIALS',
              'Vancomycin_GRD': 'OTHER ANTIBACTERIALS',
              'Voriconazole': 'ANTIMYCOTICS FOR SYSTEMIC USE',
              }
